services:
  mongodb:
    image: mongo:7
    container_name: vinyl-shop-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: vinyl_shop

volumes:
  mongodb_data:
